#pragma once

#define NO_ERROR 0

#define INVALID_ARGUMENT 100
#define INVALID_ARGUMENT_M_SIZE 101
#define INVALID_ARGUMENT_N_SIZE 102

#define INCORRECT_SIZE 200
#define INCORRECT_SIZE_M 201
#define INCORRECT_SIZE_N 202
#define INCORRECT_SIZE_MULTIPLAYING 203

#define INVALID_FILE_NAME 300
#define INCORRECT_VALUE 301
#define INCORRECT_ROW_LENGTH 302

#define INCORRECT_VECTOR_SIZE 400


